pipeline {
    agent any

    environment {
        AWS_REGION = "ap-south-1"
    }

    stages {

        stage('Checkout GitHub Repo') {
            steps {
                withCredentials([sshUserPrivateKey(credentialsId: 'github-ssh',
                                                  keyFileVariable: 'SSH_KEY')]) {
                    sh '''
                        rm -rf ec2 || true
                        GIT_SSH_COMMAND="ssh -i $SSH_KEY -o StrictHostKeyChecking=no" \
                        git clone git@github.com:Mehar-Shaba/terraform.git
                    '''
                }
            }
        }

        stage('Terraform Init') {
            steps {
                dir('terraform/ec2') {
                    withCredentials([
                        [$class: 'AmazonWebServicesCredentialsBinding',
                         credentialsId: 'aws-creds']
                    ]) {
                        sh '''
                            terraform init
                        '''
                    }
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('terraform/ec2') {
                    withCredentials([
                        [$class: 'AmazonWebServicesCredentialsBinding',
                         credentialsId: 'aws-creds']
                    ]) {
                        sh '''
                            terraform plan
                        '''
                    }
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('terraform/ec2') {
                    withCredentials([
                        [$class: 'AmazonWebServicesCredentialsBinding',
                         credentialsId: 'aws-creds']
                    ]) {
                        sh '''
                            terraform apply -auto-approve
                        '''
                    }
                }
            }
        }
    }
}
